"""audio_and_image

Revision ID: af066d38812a
Revises: c3e051b0f377
Create Date: 2025-10-12 21:40:54.968987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af066d38812a'
down_revision: Union[str, Sequence[str], None] = 'c3e051b0f377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('terms', sa.Column('image_id', sa.String(length=36), nullable=True))
    op.add_column('terms', sa.Column('audio_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'terms', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'terms', 'audios', ['audio_id'], ['id'], ondelete='SET NULL')
    op.drop_column('terms', 'image_name')
    op.drop_column('terms', 'audio_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terms', sa.Column('audio_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('terms', sa.Column('image_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'terms', type_='foreignkey')
    op.drop_constraint(None, 'terms', type_='foreignkey')
    op.drop_column('terms', 'audio_id')
    op.drop_column('terms', 'image_id')
    op.drop_table('images')
    op.drop_table('audios')
    # ### end Alembic commands ###
